apiVersion: v1
kind: Secret
metadata:
  name: lottery-secrets
  namespace: lottery-system
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:Tk55050934@lottery-db.car8cokia05m.us-east-1.rds.amazonaws.com:5432/lottery
  S3_ENDPOINT: https://s3.us-east-1.amazonaws.com
  S3_BUCKET: lottery-assets-2026
  S3_REGION: us-east-1
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123
